/* Copyright 2015 The math21 Authors. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/

// Do not edit.
// file generated by replacing "_cpu(" in cpu file to "_opencl(".

#include "template_opencl_01_f_set.h"
#include "op_opencl_01_f_set.h"

#ifdef MATH21_FLAG_USE_OPENCL

using namespace math21;

void
math21_generic_tensor_subregion_f_set_or_get_opencl(NumN fname, NumN n, PtrVoidWrapper x, PtrVoidWrapper y, NumN dims,
                                                    PtrNInWrapper dx, PtrNInWrapper dy,
                                                    PtrNInWrapper offset, NumB isGet, NumN type) {
    if (type == m21_type_NumR) {
        math21_template_tensor_subregion_f_set_or_get_opencl<NumR>(fname, n, x, y, dims, dx, dy, offset,
                                                                   isGet);
    } else if (type == m21_type_NumR32) {
        math21_template_tensor_subregion_f_set_or_get_opencl<NumR32>(fname, n, x, y, dims, dx, dy, offset,
                                                                     isGet);
    } else if (type == m21_type_NumR64) {
        math21_template_tensor_subregion_f_set_or_get_opencl<NumR64>(fname, n, x, y, dims, dx, dy, offset,
                                                                     isGet);
    } else {
        math21_tool_assert(0);
    }
}

void math21_generic_matrix_f_set_by_matrix_opencl(NumN fname, NumN d1, NumN d2,
                                                  PtrVoidInWrapper x, NumN d1_x, NumN d2_x, NumN stride1_x,
                                                  NumN stride2_x,
                                                  PtrVoidWrapper y, NumN d1_y, NumN d2_y, NumN stride1_y,
                                                  NumN stride2_y,
                                                  NumN offset_x, NumN offset_y, NumN type) {
    if (type == m21_type_NumR) {
        math21_template_matrix_f_set_by_matrix_opencl<NumR>(fname, d1, d2,
                                                            x, d1_x, d2_x, stride1_x, stride2_x,
                                                            y, d1_y, d2_y, stride1_y, stride2_y,
                                                            offset_x, offset_y);
    } else if (type == m21_type_NumR32) {
        math21_template_matrix_f_set_by_matrix_opencl<NumR32>(fname, d1, d2,
                                                              x, d1_x, d2_x, stride1_x, stride2_x,
                                                              y, d1_y, d2_y, stride1_y, stride2_y,
                                                              offset_x, offset_y);
    } else if (type == m21_type_NumR64) {
        math21_template_matrix_f_set_by_matrix_opencl<NumR64>(fname, d1, d2,
                                                              x, d1_x, d2_x, stride1_x, stride2_x,
                                                              y, d1_y, d2_y, stride1_y, stride2_y,
                                                              offset_x, offset_y);
    } else {
        math21_tool_assert(0);
    }
}

void math21_generic_tensor_3d_f_set_by_tensor_3d_opencl(NumN fname, NumN d1, NumN d2, NumN d3,
                                                        PtrVoidInWrapper x, NumN d1_x, NumN d2_x, NumN d3_x,
                                                        NumN stride1_x, NumN stride2_x, NumN stride3_x,
                                                        PtrVoidWrapper y, NumN d1_y, NumN d2_y, NumN d3_y,
                                                        NumN stride1_y, NumN stride2_y, NumN stride3_y,
                                                        NumN offset_x, NumN offset_y, NumN type) {
    if (type == m21_type_NumR) {
        math21_template_tensor_3d_f_set_by_tensor_3d_opencl<NumR>(fname, d1, d2, d3,
                                                                  x, d1_x, d2_x, d3_x,
                                                                  stride1_x, stride2_x, stride3_x,
                                                                  y, d1_y, d2_y, d3_y,
                                                                  stride1_y, stride2_y, stride3_y,
                                                                  offset_x, offset_y);
    } else if (type == m21_type_NumR32) {
        math21_template_tensor_3d_f_set_by_tensor_3d_opencl<NumR32>(fname, d1, d2, d3,
                                                                    x, d1_x, d2_x, d3_x,
                                                                    stride1_x, stride2_x, stride3_x,
                                                                    y, d1_y, d2_y, d3_y,
                                                                    stride1_y, stride2_y, stride3_y,
                                                                    offset_x, offset_y);
    } else if (type == m21_type_NumR64) {
        math21_template_tensor_3d_f_set_by_tensor_3d_opencl<NumR64>(fname, d1, d2, d3,
                                                                    x, d1_x, d2_x, d3_x,
                                                                    stride1_x, stride2_x, stride3_x,
                                                                    y, d1_y, d2_y, d3_y,
                                                                    stride1_y, stride2_y, stride3_y,
                                                                    offset_x, offset_y);
    } else {
        math21_tool_assert(0);
    }
}

void math21_generic_vector_f_set_by_value_opencl(NumN fname, NumN n, NumR value, PtrVoidWrapper x, NumN stride_x,
                                                 NumN type) {
    if (type == m21_type_NumN8) {
        math21_template_vector_f_set_by_value_opencl<NumN8>(fname, n, (NumN8) value, x, stride_x);
    } else if (type == m21_type_NumN) {
        math21_template_vector_f_set_by_value_opencl<NumN>(fname, n, (NumN) value, x, stride_x);
    } else if (type == m21_type_NumR) {
        math21_template_vector_f_set_by_value_opencl<NumR>(fname, n, (NumR) value, x, stride_x);
    } else if (type == m21_type_NumR32) {
        math21_template_vector_f_set_by_value_opencl<NumR32>(fname, n, (NumR32) value, x, stride_x);
    } else if (type == m21_type_NumR64) {
        math21_template_vector_f_set_by_value_opencl<NumR64>(fname, n, (NumR64) value, x, stride_x);
    } else {
        math21_tool_assert(0);
    }
}

#endif